# Aula 02 - Python 

## Dados numéricos 


In [8]:
# variável inteira
a = 1
print('Valor de a é igual a =' + str(a)) #aqui foi transformada a variável 'a' em 'str' para poder somar texto com texto
#número inteiro com texto nõo se soma
type(a) #aqui estou pedindo para ver qual é o tipo do dado 'a'

Valor de a é igual a =1


int

In [12]:
# variável dupla precisão
b = 1.0
print('Valor de b é igual a = ' + str(b))
type(b)

Valor de b é igual a = 1.0


float

In [11]:
#converter float para int
c = int(b)
print(c)
type(c)

1


int

In [14]:
#Declarando nan (valor não numérico) - reconhece que não é um número
import numpy as np
d = np.nan
print (d)
type(d)

nan


float

# Operação com NaN
e = d*1
print(e)
e = d + 1
print(e)
e = np.nansum([d,1])
print(e)

## Dados de texto (string)

In [23]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel" #funciona com uma ou duas aspas
print(f)
print(g)
print (f + ' ' + g)

Fábio
Gabriel
Fábio Gabriel


## Dados do tipo bool - lógico

In [24]:
a == 1

True

In [27]:
h = (a==1)
print(h)
type(h)

True


bool

In [28]:
h = (a==2)
print(h)
type(h)

False


bool

In [31]:
i = True
type(i)


bool

In [32]:
ii = 'True'
type(ii)

str

## Operação de comparação

In [36]:
#Operação == (comparação)
a==b

True

In [37]:
#Operação com > e <
a>b

False

In [38]:
#Operação != (diferente de) 

In [39]:
a!=b

False

In [40]:
#Operação >= ou <= 
a>=b

True

## Operações matemáticas

In [41]:
#Soma
a+b

2.0

In [42]:
#Soma e atribuir valor
ab= a+b
print(ab)

2.0


In [44]:
#Multiplicação
l = a*b #não use L como variável
print('Não use l como variável')
j = a*b
print(j)

Não use l como variável
1.0


In [45]:
#Divisão
a/b

1.0

In [49]:
#Potência
5**2

25

In [51]:
#Operações matemáticas com a biblioteca math
import math 

math.exp(10) #exponencial de 10

22026.465794806718

In [52]:
math.exp(a)

2.718281828459045

In [53]:
math.exp(0)

1.0

In [54]:
import math as mt
mt.exp(a)

2.718281828459045

In [55]:
mt.exp(c)

2.718281828459045

In [56]:
mt.log(c)

0.0

In [57]:
mt.log10(c)

0.0

In [58]:
mt.log10(100)

2.0

## Listas

In [63]:
myFirstList = [1, 2, 3]
print(myFirstList[0]) #coloca na tela o número que está na posição 0 da lista.
#para acessar a lista, sempre coloca entre colchetes a posição 

1


In [64]:
myFirstList==a

False

In [65]:
myFirstList[0]==a

True

In [66]:
mySecondList = [1,a,'c'] #lista com número, variável e texto
print(mySecondList)

[1, 1, 'c']


In [67]:
type(mySecondList)

list

In [68]:
type(mySecondList[0])

int

## Caminhos = path

In [70]:
path = r"C:\Users\bruna\Documents\ENS410064\ENS410064" #coloca r antes do caminho para ele aceitar a barra virada
print(path)

C:\Users\bruna\Documents\ENS410064\ENS410064


In [74]:
path = "C:/Users/bruna/Documents/ENS410064/ENS410064" #troca a barra do caminho para o outro lado
print(path)

C:/Users/bruna/Documents/ENS410064/ENS410064


In [76]:
import os
os.listdir(path) #listar arquivos na pasta

['.git', '.gitignore', 'dados', 'pyenv', 'README.md', 'scripts']

In [77]:
os.listdir(path)[0] #selecionar o arquivo que está na primeira posição da lista

'.git'

In [80]:
path+"/"+os.listdir(path)[0] #concatenando caminhos

'C:/Users/bruna/Documents/ENS410064/ENS410064/.git'

In [83]:
os.listdir(path+"/"+os.listdir(path)[0]) #mostra o que tem na pasta que está na posição 0, dentro da pasta 'path'

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [87]:
os.getcwd() #mostra o diretório no qual estou trabalhando

'C:\\Users\\bruna\\Documents\\ENS410064\\ENS410064\\pyenv\\Scripts'

In [89]:
os.chdir('C:\\Users\\bruna\\Documents\\ENS410064\\') #mudo para outro diretório, para o caminho listado (agora estou trabalhando nesse)

In [90]:
os.getcwd()

'C:\\Users\\bruna\\Documents\\ENS410064'

In [94]:
new_path = (os.getcwd()+'/test') #cria uma variável, que cria um diretorio na pasta que estava trabalhando

if os.path.isdir(new_path):
    print('diretório já existe')
else: 
    print('Criando diretório' + new_path)
    os.mkdir(new_path)

diretório já existe


In [97]:
new_path = (os.getcwd()+'/test2') #cria uma variável, que cria um diretorio na pasta que estava trabalhando

if os.path.isdir(new_path):
    print('diretório já existe')
    #criando um arquivo de texto dentro do diretório que já existe
    with open(new_path+"/copy.txt","w") as file:
        file.write("Your text goes here")
else: 
    print('Criando diretório' + new_path)
    os.mkdir(new_path)

Criando diretórioC:\Users\bruna\Documents\ENS410064/test2


## Numpy arrays e Pandas dataframes

In [99]:
import numpy as np 
#criando uma variável numpy
n = np.array(0) #sempre quando chama função, são parênteses. Sempre que são índices, colchetes.
type(n)

numpy.ndarray

In [100]:
#Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList) #transforma a lista em uma numpy array
print(n)

[ 1  2  3 10 20 55]


In [105]:
n = np.random.rand(10,10) #gera uma matriz aleatória 10 x 10
print(n)
print(n.shape) #printa o tamanho (dimensões) da matriz

[[0.43808646 0.99969139 0.75933296 0.75639424 0.13141551 0.49696492
  0.30202119 0.05476799 0.79464125 0.66796861]
 [0.44322819 0.74078508 0.73127622 0.79432055 0.11108605 0.88932797
  0.43475762 0.03852436 0.23834066 0.61511445]
 [0.03935936 0.79763372 0.0640726  0.27945224 0.52005313 0.73963096
  0.61064252 0.19041118 0.41384887 0.7631352 ]
 [0.71395434 0.27010389 0.47685711 0.03439655 0.57923998 0.58604605
  0.19449321 0.8114511  0.6977146  0.10604788]
 [0.43281053 0.13904893 0.49779789 0.79852072 0.52584656 0.75819952
  0.22544903 0.47861296 0.59489847 0.99985529]
 [0.86319284 0.62642992 0.69504881 0.48038922 0.97878955 0.92065871
  0.93843228 0.02878296 0.68767253 0.89244198]
 [0.02845015 0.18516262 0.54097698 0.1383122  0.64342327 0.44070331
  0.4182143  0.37192859 0.77415157 0.67892279]
 [0.47681607 0.15616763 0.84639161 0.07253916 0.984993   0.86005567
  0.34579436 0.62508196 0.97179422 0.60981083]
 [0.5449134  0.23351385 0.36909031 0.83591214 0.49307816 0.02549667
  0.79559718

In [106]:
#Acessando valores da matriz
n[0,0] #mostra o que está na posição 0,0 da matriz

0.4380864615969945

In [107]:
n[0] #mostra a primeira linha da matriz

array([0.43808646, 0.99969139, 0.75933296, 0.75639424, 0.13141551,
       0.49696492, 0.30202119, 0.05476799, 0.79464125, 0.66796861])

In [108]:
n[0,:] #primeira linha, todas as colunas

array([0.43808646, 0.99969139, 0.75933296, 0.75639424, 0.13141551,
       0.49696492, 0.30202119, 0.05476799, 0.79464125, 0.66796861])

In [109]:
n[:,0] #todas as linhas, primeira coluna

array([0.43808646, 0.44322819, 0.03935936, 0.71395434, 0.43281053,
       0.86319284, 0.02845015, 0.47681607, 0.5449134 , 0.65118326])

In [110]:
n[:,1:5] #todas as linhas, da coluna 1 a 5

array([[0.99969139, 0.75933296, 0.75639424, 0.13141551],
       [0.74078508, 0.73127622, 0.79432055, 0.11108605],
       [0.79763372, 0.0640726 , 0.27945224, 0.52005313],
       [0.27010389, 0.47685711, 0.03439655, 0.57923998],
       [0.13904893, 0.49779789, 0.79852072, 0.52584656],
       [0.62642992, 0.69504881, 0.48038922, 0.97878955],
       [0.18516262, 0.54097698, 0.1383122 , 0.64342327],
       [0.15616763, 0.84639161, 0.07253916, 0.984993  ],
       [0.23351385, 0.36909031, 0.83591214, 0.49307816],
       [0.67559624, 0.62610334, 0.52273856, 0.96941681]])

In [111]:
n[0, 1:5]

array([0.99969139, 0.75933296, 0.75639424, 0.13141551])

In [112]:
n[0,-1] #mostra o ultimo valor da linha zero

0.6679686135256101

In [113]:
n[0,4:-1]

array([0.13141551, 0.49696492, 0.30202119, 0.05476799, 0.79464125])

In [116]:
an = np.log(n) #aplicou o log em todos os valores da matriz
print (an)

[[-8.25338987e-01 -3.08661253e-04 -2.75314912e-01 -2.79192551e-01
  -2.02939115e+00 -6.99235840e-01 -1.19725809e+00 -2.90464943e+00
  -2.29864523e-01 -4.03514092e-01]
 [-8.13670545e-01 -3.00044741e-01 -3.12964031e-01 -2.30268183e-01
  -2.19745017e+00 -1.17289195e-01 -8.32966588e-01 -3.25646457e+00
  -1.43405428e+00 -4.85946927e-01]
 [-3.23502139e+00 -2.26105789e-01 -2.74773849e+00 -1.27492389e+00
  -6.53824308e-01 -3.01603917e-01 -4.93243573e-01 -1.65856944e+00
  -8.82254419e-01 -2.70320062e-01]
 [-3.36936268e-01 -1.30894863e+00 -7.40538388e-01 -3.36979911e+00
  -5.46038415e-01 -5.34356901e-01 -1.63735802e+00 -2.08931151e-01
  -3.59945146e-01 -2.24386459e+00]
 [-8.37455232e-01 -1.97292939e+00 -6.97561119e-01 -2.24994359e-01
  -6.42745827e-01 -2.76808715e-01 -1.48966116e+00 -7.36863022e-01
  -5.19364524e-01 -1.44721565e-04]
 [-1.47117155e-01 -4.67718369e-01 -3.63773204e-01 -7.33158629e-01
  -2.14386288e-02 -8.26658797e-02 -6.35445821e-02 -3.54797165e+00
  -3.74442530e-01 -1.13793779e-01